ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@playwright/test'
  - docsify
  - esbuild
  - msw
  - prisma
  - unrs-resolver
