ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - '@firebase/util'
  - '@playwright/test'
  - '@prisma/client'
  - '@prisma/engines'
  - docsify
  - esbuild
  - msw
  - prisma
  - protobufjs
  - unrs-resolver
