onlyBuiltDependencies:
  - '@firebase/util'
  - '@playwright/test'
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - docsify
  - esbuild
  - msw
  - prisma
  - protobufjs
  - unrs-resolver
