name: 'Enhanced Prisma Client Generation'
description: 'Generate Prisma client with debugging information'
inputs:
  database_url:
    description: 'The database URL to use for Prisma client generation'
    required: true
    default: 'file:./prisma/data.db'

runs:
  using: 'composite'
  steps:
    - name: 🛠 Generate Prisma Client
      shell: bash
      run: |
        # Force clean any existing generated client
        # rm -rf node_modules/.prisma

        # Show the current branch for debugging
        # echo "Current branch: $GITHUB_REF"

        # Show the schema file for debugging
        # echo "Prisma schema content:"
        # cat prisma/schema.prisma

        # Generate the client with explicit path
        npx prisma generate

        # Verify the generated client
        ls -la node_modules/.prisma/client || echo "Client directory not found!"

        # Check if index.d.ts contains the Team and TeamLeader types
        echo "Checking for Team and TeamLeader types in generated client:"
        grep -E "Team|TeamLeader" node_modules/.prisma/client/index.d.ts || echo "Types not found!"
      env:
        DATABASE_URL: ${{ inputs.database_url }}
        DEBUG: 'prisma:*'
