name: Playwright Tests (Manual)
on:
  workflow_dispatch: # Manual trigger only
    inputs:
      environment:
        description: "Environment to test against"
        required: false
        default: "local"
        type: choice
        options:
          - local
          - staging

jobs:
  playwright:
    uses: ./.github/workflows/playwright-reusable.yml
    with:
      environment: ${{ inputs.environment || 'local' }}
      upload_artifact_suffix: "-manual"
